### ISSUE TITLE
can't check on Coin Rate

### ISSUE THREAD

**Issue by ghost** [umayanga123/scpp_android_node#10]
now can't check on the coin rate function instantly. It worked after the 2016-9-3 @umayanga123 push. But now this error comes although Base is running.
![image](https://cloud.githubusercontent.com/assets/8732484/18232602/73d51876-72f0-11e6-9735-a455ef73db1b.png)

**Comment by umayanga123** [comment]
No error.please, check again

**Comment by ghost** [comment]
yes it's working and i reported about that in Trello Agile board.
