### ISSUE TITLE
Send Money Fail Error

### ISSUE THREAD

**Issue by ghost** [umayanga123/scpp_android_node#11]
all required component are running, but Minner is Not Responding as always.
![image](https://cloud.githubusercontent.com/assets/8732484/18258989/d752172a-73fc-11e6-961f-0304cd8d648e.png)
When send a coin, coin appears at the other user's wallet with a notification, BUT at the sender's side coin remains the same and a error called "Send Money Fail Error" comes after some time. @umayanga123 
![image](https://cloud.githubusercontent.com/assets/8732484/18259033/559485f0-73fd-11e6-9ba7-29136e8e3c31.png)
![image](https://cloud.githubusercontent.com/assets/8732484/18259045/6faab450-73fd-11e6-8924-66456d437a3a.png)

**Comment by umayanga123** [comment]
I think this  is some trouble in your miner key , I advice please Drop all database and also delete , ShredPreferense file to , and run and test.

**Comment by ghost** [comment]
fixed when delete `sharedPreference` files.
