### ISSUE TITLE
P2P Transactions require users to be in Transactions page at same time

### ISSUE THREAD

**Issue by ghost** [umayanga123/scpp_android_node#12]
@umayanga123 `p2p` not works still when the other user at the receiving end is in a different page except `Transaction` page.

**Comment by umayanga123** [comment]
@Iresha92  , we will add to it Home page to in this time........! as new sprint back log and , hope this keep as , final sprint before Interim....!!!

**Comment by ghost** [comment]
That sounds good

**Comment by umayanga123** [comment]
now i think this is ok.
