### ISSUE TITLE
Cannot calculate the real distance between two locations in carpooling service,it still give shortest distance.

### ISSUE THREAD

**Issue by Dulakshi** [umayanga123/scpp_android_node#15]
In carpooling app it give the shortest distance between start and stop ride points not real riding distance.

**Comment by umayanga123** [comment]
@Dulakshi  ,please discuss with me , sep 9 meeting. As I remember ,you don't told to me ,how do that implementation and limitation.

**Comment by umayanga123** [comment]
I think ,it is good for reserving future developers.now we move to research.
