### ISSUE TITLE
Cannot keep multiple user detail ,because still overwrite 'SharePreferense' file.

### ISSUE THREAD

**Issue by ghost** [umayanga123/scpp_android_node#4]
Cannot keep multiple user details,because still overwrite 'SharePreference' file. And it's not that practical to keep multiple data in sharedpreference. So it seems better to use sqlite db concurrently with sharedpreference.

**Comment by umayanga123** [comment]
Fix this issue. but same private key and public key use multiple users. hope is not be issue in this stage.
