### ISSUE TITLE
Google Map Not working

### ISSUE THREAD

**Issue by ghost** [umayanga123/scpp_android_node#6]
Google map of services menu is not working.

**Comment by umayanga123** [comment]
My opinion if you are can build simple map activity in seperate project and if it ok, correct working project app. but don't go copy past thing. this is our working product so it should be table every time.

**Comment by Dulakshi** [comment]
Generated API key related to the project package. Load the Google mapView. 
Not yet added current location to the mapview.

**Comment by umayanga123** [comment]
please , I comment your last commit. @Dulakshi  check it.

**Comment by Dulakshi** [comment]
Map view functionalities implemented to view current location and calculate distance between start and stop points

**Comment by umayanga123** [comment]
I change app key and fully clear cache data and uninstall application ,after rebuild app working fine both AVD and real device.but still not sure the error is slove.
![b](https://cloud.githubusercontent.com/assets/7321656/18097807/15f1a3e2-6efd-11e6-9035-33704ec3bc90.png)

**Comment by ghost** [comment]
when click on "car pooling" app stops AVD emulator where Google Maps app is fully working properly with GPS. @umayanga123  @Dulakshi 
![image](https://cloud.githubusercontent.com/assets/8732484/18224712/c6227c4e-71fc-11e6-978c-032ba2cdaca2.png)
![image](https://cloud.githubusercontent.com/assets/8732484/18224757/ca23fdc6-71fd-11e6-8ea1-f74190671e16.png)
![image](https://cloud.githubusercontent.com/assets/8732484/18224763/deaf0d62-71fd-11e6-95ac-296670527c85.png)

**Comment by umayanga123** [comment]
I guess first bug some hardware ISSUE. I have only one solution remain , You generate your own app key and put and try again. @Iresha92  it is ok ,then I will again check app key.
