### ISSUE TITLE
Wallet Implementation

### ISSUE THREAD

**Issue by ghost** [umayanga123/scpp_android_node#7]
Although Wallet is listed in the main menu, Neither Wallet layout is added yet nor any functionality.

**Comment by umayanga123** [comment]
#not add Wallet_Layout different because, wallet is all ready implement in Money transfer. I don't add wallte navigation it may be confused.i told about this Dulakshi , please contact her further information.

**Comment by ghost** [comment]
@umayanga123  has developed it. and the coin rate is available for users now with a simple average calculation.
![image](https://cloud.githubusercontent.com/assets/8732484/18262113/1f49e03e-741c-11e6-912a-f1a34519f46b.png)
