### ISSUE TITLE
Transactions Menu Item and Profile Menu Item Implementation

### ISSUE THREAD

**Issue by ghost** [umayanga123/scpp_android_node#8]
- **Transactions Menu Item** should be connected with wallet to enable users to see their current total balance etc. 
- **Profile Menu Item** should contain a search bar and other necessary functionalities.
- There should be a top menu bar to navigate to common functions such as to _Home_, to _Logout._

**Comment by umayanga123** [comment]
Profile Menu Item should contain a search bar - (optional)
